### PR TITLE
add arm64 support for osx and linux

### PR DESCRIPTION
**Pull request by gbarter**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by gbarter** [comment]
@conda-forge-admin, please rerender

**Comment by gbarter** [comment]
SMT Toolbox Maintainers : We love this package and it would be great to have native support for ARM processors (Mac Silicon & Linux Aarch64/Docker).  Let me know if this PR poses any issues for you.

**Comment by gbarter** [comment]
@conda-forge-admin, please rerender

**Comment by relf** [comment]
Thanks!

**Pull request merged**
